import turtle
#Screen
Instruc = turtle.Screen()
Instruc.bgcolor("black")
Instruc.title("Instructions")

#Border
Border = turtle.Turtle()
Border.speed(0)
Border.color("Purple")
Border.penup()
Border.setposition(-300,-300)
Border.pensize(5)
Border.pendown()
for side in range(4):
    Border.fd(600)
    Border.lt(90)
Border.hideturtle()

#Instructions
Play = turtle.Turtle()
Play.color("White")
Play.speed(0)
Play.penup()
Play.setposition(0,200)
Play.write('How To Play', font=("Courier", 40, "bold"), align='center')
Play.hideturtle()

#Controls
Player = turtle.Turtle()
Player.hideturtle()
turtle.register_shape("Spaceship.gif")
Player.shape("Spaceship.gif")
Player.speed(0)
Player.penup()
Player.setposition(-250, 100)
Player.showturtle()

player = turtle.Turtle()
player.color("white")
player.speed(0)
player.penup()
player.setposition(-200, 90)
player.write("Move the ship by using the left and right", font=("Courier", 15, "bold"), align= 'left')
player.setposition(-200, 60)
player.write("arrow keys and press space to shoot at", font=("Courier", 15, "bold"), align= 'left')
player.setposition(-200,30)
player.write("the aliens.", font=("Courier", 15, "bold"), align= 'left')
player.hideturtle()

#How the game works
enemy = turtle.Turtle()
enemy.color("white")
enemy.speed(0)
enemy.penup()
enemy.setposition(-250, -10)
turtle.register_shape("alien.gif")
enemy.shape("alien.gif")
enemy.showturtle()

enemyone = turtle.Turtle()
enemyone.color("white")
enemyone.speed(0)
enemyone.penup()
enemyone.setposition(-250, -110)
enemyone.shape("alien.gif")
enemyone.showturtle()

enemytwo = turtle.Turtle()
enemytwo.color("white")
enemytwo.speed(0)
enemytwo.penup()
enemytwo.setposition(-250, -210)
enemytwo.shape("alien.gif")
enemytwo.showturtle()

Enemy = turtle.Turtle()
Enemy.hideturtle()
Enemy.color("white")
Enemy.speed(0)
Enemy.penup()
Enemy.setposition(-200, -10)
Enemy.write ( "These aliens are the enemies, they", font=("Courier", 15, "bold"), align= 'left')
Enemy.setposition(-200, -40)
Enemy.write ( "will attack you. Your job is to destroy", font=("Courier", 15, "bold"), align= 'left')
Enemy.setposition(-200, -70)
Enemy.write ( "them and prevent them from reaching your", font=("Courier", 15, "bold"), align= 'left')
Enemy.setposition(-200, -100)
Enemy.write ( "ship. If an alien reaches your ship ", font=("Courier", 15, "bold"), align= 'left')
Enemy.setposition(-200, -130)
Enemy.write ( "its GAME OVER. Each alien is worth", font=("Courier", 15, "bold"), align= 'left')
Enemy.setposition(-200, -160)
Enemy.write ( "10 points try to get the highest", font=("Courier", 15, "bold"), align= 'left')
Enemy.setposition(-200, -190)
Enemy.write ( "score possible, Good Luck!", font=("Courier", 15, "bold"), align= 'left')

turtle.done()


